### PR TITLE
Initial PDF and AudioBook format draft

### PR DESCRIPTION
**Pull request by io7m**
This is the initial draft of the PDF and AudioBook formats for bookmarks.

### CODE REVIEW

**Review by mauricecarrier7 — APPROVED** [review]
LGTM!

**Review by nunommts — APPROVED** [review]

**Review by vladimirfedorov — APPROVED** [review]
Looks good to me

**Comment by ray-lee** [comment]
Do we have any examples of audiobooks that have more than one part? I'm not sure I've seen what that looks like.

Looking at a random findaway audiobook, I see this in the manifest:
```
  "readingOrder": [
    {
      "type": "audio/mpeg",
      "title": "Track 1",
      "duration": 1007.49,
      "findaway:part": 0,
      "findaway:sequence": 1
    },
    ...
  ]
```
Would the chapter number here be 0 (the position in `readingOrder`), or 1 (the `findaway:sequence` value, which appears to be 1-based)?

**Comment by io7m** [comment]
This is a good point. The spec doesn't have anything to say about this.

I think parts are a purely a Findaway-specific abstraction. I'm pretty sure we infer, in both apps, the integer chapter number from the `readingOrder` as you described. I think we largely depend on book authors to decide which order chapters are supposed to be in, and they're supposed to do that via the `readingOrder`. The question would be whether the chapter and part numbers that go into the bookmark are the chapter and part numbers from the `findaway:` fields, or if we assume `part` is always `0` and fetch the chapter number from `readingOrder[i]` where `i` is the number given in the bookmark. :sweat:

**Comment by io7m** [comment]
I mean... We just need to pick which interpretation we prefer and update both apps at the same time.

**Comment by ray-lee** [comment]
In an audiobook with multiple parts, is `readingOrder` still a flat list? If so, I think the presence of `part` in the bookmark would imply that we need to look at the `findaway:part` property to find the right part, and therefore that we need to look at the `findaway:sequence` property to find the right chapter. Does that make sense?

**Comment by io7m** [comment]
`readingOrder` is always a flat list, yeah. At least in every manifest I've ever seen.

Also, yes, I think we need to search for `findaway:part`. I think the (generalized) algorithm is this:

Given a bookmark with part `P` and chapter `C`, look in the `readingOrder` for an entry with part `Q` and chapter `D` such that `P  = Q` and `C = D` by checking for `findaway:part` and `findaway:sequence` elements. If no such entry exists, then behave as if `P = 0` and choose `readingOrder[C]`. 

This is simple to implement on the Android side because the Findaway player and the Open Access player are two different implementations, and so each implementation only needs to implement their own half of the algorithm. We don't need to worry about, for example, `findaway:sequence` being 1-based because the Open Access player will never see a bookmark that uses a `findaway:sequence` value, and so on.

The Open Access player can assume that it'll never see a manifest that has `findaway` elements, and the Findaway player can assume they're always there.

**Comment by io7m** [comment]
I'm pretty sure the Android side already does all of the above, but someone will need to check.

**Comment by ray-lee** [comment]
Thanks, that makes sense. Last question: For overdrive audiobooks, I assume there won't be `findaway:part` and `findaway:sequence` properties, and that we just need to map `part` and `chapter` to some other properties. Do we know what those are? I haven't seen an overdrive audiobook manifest yet.

**Comment by io7m** [comment]
Overdrive manifests are in an essentially proprietary format, and they don't use parts. We can assume `part` is always `0` and use `chapter` as an index into the resulting playlist in the same manner.

**Comment by ray-lee** [comment]
@io7m Cool. Would you mind adding those answers somewhere in the spec? Hopefully that will be enough to ensure we end up with similar implementations.

**Comment by io7m** [comment]
Added!

**Comment by io7m** [comment]
https://github.com/ThePalaceProject/mobile-specs/pull/2

When that PR is merged, I'll archive this repository.

**Pull request merged**
